### ISSUE TITLE
gmap.gff3结果文件为空

### ISSUE THREAD

**Issue by 88Zoe** [sc-zhang/AlleleFinder#11]
张老师，您好！
我是利用AlleleFinder鉴定4倍体中的等位基因。
其他结果文件中都有内容，但是02.gmap文件夹中gmap.gff3文件是空的，里面的CpDB文件夹中有内容，这样的结果是正常的吗？？

我使用的gmap版本为：version 2024-10-10 
请老师帮忙解答，感谢！！

------------------------------------------
![微信图片_20241127110848](https://github.com/user-attachments/assets/126c8f4e-5a1c-4156-85b9-af5f9f994605)
![微信图片_20241127110430](https://github.com/user-attachments/assets/9873d1ba-4678-4679-96ec-b7dcfcb71f08)
----------------------------------------

**Comment by sc-zhang** [comment]
It seems there was something wrong with gmap, maybe you can run the gmap manually with the command in the log file, and check if it can generate gmap.gff3 or not.

**Comment by 88Zoe** [comment]
张老师，

我把gmap步骤从log文件中单独取出后，在gmap前面加上绝对路径时，能够生成gmap.gff3，但是不加绝对路径，即使设置了环境变量或者source activate 环境，gmap.gff3依旧为空。
————————————————————————————————————————————
~/miniconda3/envs/gmap_2024_10_10/bin/gmap -D . -d CpDB -f  -n  -t  cds.fa > gmap.gff3  (有结果)

但是设置环境变量，或者source activate 环境，之后直接gmap -D . -d CpDB -f  -n  -t  cds.fa > gmap.gff3  (gmap.gff3为空)
——————————————————————————————————————————————

请问张老师，有什么办法可以解决吗？

感谢~~~~

**Comment by sc-zhang** [comment]
It seems caused by the mismatch of gmap and gmap_build. Please use "which" command to check which gmap you run after source activate environment or add it to the "PATH" environment variable. There may exist another gmap with higher priority than the correct one.

**Comment by 88Zoe** [comment]
感谢您的及时回复，我使用"which"命令只发现一个gmap.
___________________________________________________
$which gmap
~/miniconda3/envs/gmap_2024_10_10/bin/gmap
$which gmap_build
~/miniconda3/envs/gmap_2024_10_10/bin/gmap_build
_______________________________________________________________

**Comment by sc-zhang** [comment]
Use gmap -D . -d CpDB -f -n -t cds.fa 1> gmap.gff3 2>gmap.err after source activate environment or add it to the "PATH" environment variable, then if gmap.gff3 is empty check the gmap.err file

**Comment by 88Zoe** [comment]
还是一样，设置环境变量或者source activate , 使用相对路径gmap.gff3为空，gmap.err为空，如果可以的话，能否告诉我在AlleleFinder的流程中，可以去哪几个脚本中设置gmap的绝对路径。

谢谢~~~
--------------------------------------------------------------------------------------------------------------------------------
![微信图片_20241205160259](https://github.com/user-attachments/assets/9bd60693-cf32-4c2c-ad78-ec8814ad59de)

**Comment by sc-zhang** [comment]
Well, that is confusing. If you want set the gmap with absolute path, for the newest version just open "allele_finder/utils/runner.py" and add the path in front of all gmap from line 44 to line 63
![Snipaste_2024-12-05_16-11-46](https://github.com/user-attachments/assets/fe36e805-ab6f-4e09-b80e-1c7df9a99afa)


For the version 1.1.0 and before, open the "bin/run_gmap.py", and do the same thing in line 16 to 27
![Snipaste_2024-12-05_16-15-54](https://github.com/user-attachments/assets/fa01bedc-fc31-4819-ad92-77560ea280cd)

**Comment by 88Zoe** [comment]
好的，感谢您的耐心解答~~
