### ISSUE TITLE
GMAP not found, Aborting

### ISSUE THREAD

**Issue by 88Zoe** [sc-zhang/AlleleFinder#8]
Hello,shengcheng.

Although GMAP has been installed using conda and its path is set in the environment variables, I am still encountering the error message: "GMAP not found, Aborting..."

What should I do ?

Looking forward to hearing from you.
![GMAP_not_found](https://github.com/user-attachments/assets/650fbf07-6933-4625-a0f9-042f92067499)

Thank you.

**Comment by sc-zhang** [comment]
Please show me the result of one of the commands below.
```bash
which gmap
```
or
```bash
gmap --version
```

**Comment by 88Zoe** [comment]
I have tried two versions of gmap, when I used one of them, I would set '#' to another one's path in the environment variable to avoid conflict.  
Here are the results of  “gmap --version” are as following:
(1)
$gmap --version
Note: gmap.avx512 does not exist.  For faster speed, may want to compile package on an AVX512 machine
Note: gmap.avx2 does not exist.  For faster speed, may want to compile package on an AVX2 machine
GMAP version 2021-08-25 called with args: gmap.sse42 --version

GMAP: Genomic Mapping and Alignment Program
Part of GMAP package, version 2021-08-25
Build target: x86_64-conda-linux-gnu
Features: pthreads enabled, no alloca, zlib available, mmap available, littleendian, sigaction available, 64 bits available
Popcnt: mm_popcnt builtin_popcount
Builtin functions: builtin_clz builtin_ctz builtin_popcount
SIMD functions compiled: SSE2 SSSE3 SSE4.1 SSE4.2
Sizes: off_t (8), size_t (8), unsigned int (4), long int (8), long long int (8)
Default gmap directory (compiled): ~/miniconda3/envs/gmap/share
Default gmap directory (environment): ~/envs/gmap/share
Thomas D. Wu, Genentech, Inc.
Contact: twu@gene.com

(2)
gmap --version
Note: gmap.avx512 does not exist.  For faster speed, may want to compile package on an AVX512 machine
Note: gmap.avx2 does not exist.  For faster speed, may want to compile package on an AVX2 machine
GMAP version 2024-10-10 called with args: gmap.sse42 --version

GMAP: Genomic Mapping and Alignment Program
Part of GMAP package, version 2024-10-10
Build target: x86_64-conda-linux-gnu
Features: pthreads enabled, no alloca, zlib available, mmap available, littleendian, sigaction available, 64 bits available
Popcnt: mm_popcnt builtin_popcount
Builtin functions: builtin_clz builtin_ctz builtin_popcount
SIMD functions compiled: SSE2 SSSE3 SSE4.1 SSE4.2
Sizes: off_t (8), size_t (8), unsigned int (4), long int (8), long long int (8)
Default gmap directory (compiled): ~/miniconda3/envs/gmap_2024_10_10/share
Default gmap directory (environment): ~/gmap_2024_10_10/share
Thomas D. Wu, Genentech, Inc.
Contact: twu@gene.com

**Comment by sc-zhang** [comment]
I have test with conda, but could not reproduce this problem.
If you use a cluster like SLURM, SGE or others, please check the conda environment activate command is written in the script before the allelefinder command, or just add "export PATH=/path/to/gmap/bin:$PATH" before the allefinder command, and test if it works or not.

**Comment by 88Zoe** [comment]
Thank you for your quick response. 
When I used the older version of AlleleFinder released in September, the pipeline completed successfully.
However, the latest version does not work.

**Comment by sc-zhang** [comment]
There must something wrong with the dependencies checker, 
if you have some spare time, please save the script below to a python script like: a.py
```python
from subprocess import Popen, PIPE


class DependChecker:
    def __init__(self):
        pass

    @staticmethod
    def check(cmd):
        p = Popen(cmd, stdout=PIPE, stderr=PIPE, shell=True, encoding='utf-8')
        res, _ = p.communicate()
        print("STDOUT")
        print(res)
        print("STDERR")
        print(_)
        if res:
            return True
        return False

print(DependChecker.check("gmap --version"))
```
then run the command below
```bash
python3 a.py
```
and paste the result here.

**Comment by 88Zoe** [comment]
The result is  as follows:
----------------------------------------------------------------------------------------------------------------------------
$python a.py
STDOUT

GMAP: Genomic Mapping and Alignment Program
Part of GMAP package, version 2024-10-10
Build target: x86_64-conda-linux-gnu
Features: pthreads enabled, no alloca, zlib available, mmap available, littleendian, sigaction available, 64 bits available
Popcnt: mm_popcnt builtin_popcount
Builtin functions: builtin_clz builtin_ctz builtin_popcount
SIMD functions compiled: SSE2 SSSE3 SSE4.1 SSE4.2
Sizes: off_t (8), size_t (8), unsigned int (4), long int (8), long long int (8)
Default gmap directory (compiled): ~/miniconda3/envs/gmap_2024_10_10/share
Default gmap directory (environment): ~/miniconda3/envs/gmap_2024_10_10/share
Thomas D. Wu, Genentech, Inc.
Contact: twu@gene.com


STDERR
Note: gmap.avx512 does not exist.  For faster speed, may want to compile package on an AVX512 machine
Note: gmap.avx2 does not exist.  For faster speed, may want to compile package on an AVX2 machine
GMAP version 2024-10-10 called with args: gmap.sse42 --version

True
--------------------------------------------------------------------------------------------------------------------------------

Thank you.

**Comment by sc-zhang** [comment]
Thanks, it is real confusing that the codes of dependencies checker in allelefinder is almost same with the test script, and the result of test script is "True" but the one in allelefinder report "GMAP not found".
Anyway, if the old version works fine, just use it, for the new version, the dependencies checker was updated that if the depend software could not be found, more information would be reported.
